<a href="https://colab.research.google.com/github/RanaweeraHK/Pytorch-Zero-to-Master/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors equal to numpy ndarrays. Use to encode the inputs ,outputs and the parameters of a model .

In [1]:
import torch
import numpy as np

# 1. Initializing tensor

In [3]:
# 1. directly from data

x = [[1,2],[3,4]]
x_tensor = torch.tensor(x)
x_tensor

tensor([[1, 2],
        [3, 4]])

In [5]:
# 2. From a numpy array

np_array = np.array(x)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [13]:
# 3. From another tensor
x_ones = torch.ones_like(x_tensor)
x_ones

x_rand = torch.rand_like(x_tensor, dtype = torch.float)
x_rand

tensor([[0.7930, 0.3687],
        [0.1738, 0.3012]])

In [15]:
# 4. random or constant values

shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1168, 0.3879, 0.8579],
        [0.3124, 0.4791, 0.2515]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# 2. Attributes of a tensor

In [21]:
tensor = torch.rand(3,4)

print(f"Shape:{tensor.shape}")
print(f"Datatype:{tensor.dtype}")
print(f"Device: {tensor.device}")

Shape:torch.Size([3, 4])
Datatype:torch.float32
Device: cpu


In [27]:
# Move the tensors to acceleration, default creates in cpu
if torch.accelerator.is_available():
  tensor = tensor.to(torch.accelerator.current_accelerator)

# 3. Operations

In [29]:
tensor = torch.ones(4,4)

print(f"First row:{tensor[0]}")
print(f"First column:{tensor[:,0]}")
print(f"Last column:{tensor[:,-1]}")

# values assigning
tensor[:,1] =2
print(tensor)

First row:tensor([1., 1., 1., 1.])
First column:tensor([1., 1., 1., 1.])
Last column:tensor([1., 1., 1., 1.])
tensor([[1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.]])


In [38]:
# joining tensors

#  dim =0 --> row wise
#  dim =1 --> column wise

t = torch.cat([tensor, tensor, tensor], dim=1)
t

tensor([[1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1.],
        [1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1.],
        [1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1.],
        [1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1.]])

In [42]:
#  Matrix multiplication between tensors
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

# Element wise multiplication
y3 = tensor*tensor
y4 = tensor.mul(tensor)

print(y1)
print(y2)
print(y3)
print(y4)

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])
tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])
tensor([[1., 4., 1., 1.],
        [1., 4., 1., 1.],
        [1., 4., 1., 1.],
        [1., 4., 1., 1.]])
tensor([[1., 4., 1., 1.],
        [1., 4., 1., 1.],
        [1., 4., 1., 1.],
        [1., 4., 1., 1.]])


In [45]:
# all tensor values into one value
agg = tensor.sum() # type is tensor
agg  =agg.item() # type is int
agg

20.0

In [50]:
# in place operation
print(f"tensor before:{tensor}")
tensor.add_(5) # replace the tensor values
print(f"tensor after:{tensor}")

tensor before:tensor([[1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.]])
tensor after:tensor([[6., 7., 6., 6.],
        [6., 7., 6., 6.],
        [6., 7., 6., 6.],
        [6., 7., 6., 6.]])


# 4. Bride with numpy

In [51]:
t = torch.ones(3)
print(f"t:{t}")

n= t.numpy()
print(f"n:{n}")

t:tensor([1., 1., 1.])
n:[1. 1. 1.]


In [52]:
t.add_(3)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([4., 4., 4.])
n:[4. 4. 4.]


In [55]:
n = np.ones(5)
print(f"n:{n}")

t = torch.from_numpy(n)
print(f"t:{t}")

n:[1. 1. 1. 1. 1.]
t:tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [56]:
np.add(n,1 , out=n)
print(f"n:{n}")
print(f"t:{t}")

n:[2. 2. 2. 2. 2.]
t:tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
